In [1]:
import pandas as pd

خواندن دیتاست

In [2]:
df = pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

ایجاد مدل طبقه بند کا همسایه

In [3]:
from sklearn.neighbors import KNeighborsClassifier

In [4]:
model = KNeighborsClassifier(n_neighbors=5)

In [5]:
y = df['Outcome']
X = df.drop('Outcome', axis=1)
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [6]:
model.fit(X, y)

KNeighborsClassifier()

استفاده از مدل

In [7]:
model.predict([
    [1, 86, 57, 37, 100, 26, 0.2, 35],
    [4, 86, 57, 37, 100, 41, 0.2, 27],
              ])

C:\Users\Hamid\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0, 0], dtype=int64)

In [8]:
yhat = model.predict(X)
yhat[:10]

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [9]:
y.values[:10]

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

ارزیابی کیفیت مدل

In [10]:
import numpy as np
(len(yhat)-np.sum(abs(y.values-yhat)))/len(yhat)

0.8033854166666666

In [11]:
np.sum(y.values==yhat)/len(yhat)

0.8033854166666666

چرخ را از اول اختراع نکنیم. استفاده از امکانات کتابخانه

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
accuracy_score(y, yhat)

0.8033854166666666

معیار اکیوریسی برای داده نامتعادل خوب نیست. دلیلش در کلاس بحث شد

معیارهای ارزیابی بهتری برای این موارد وجود دارد

تئوری معیارهای ارزیابی مختلف در کلاس تدریس شد

In [20]:
from sklearn.metrics import  f1_score, classification_report, confusion_matrix

In [21]:
f1_score(y, yhat)

0.6986027944111777

In [22]:
print(classification_report(y, yhat))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85       500
           1       0.75      0.65      0.70       268

    accuracy                           0.80       768
   macro avg       0.79      0.77      0.78       768
weighted avg       0.80      0.80      0.80       768



In [23]:
confusion_matrix(y, yhat)

array([[442,  58],
       [ 93, 175]], dtype=int64)

ارزیابی مدل با همان داده ای که برای ساخت مدل استفاده شده کار صحیحی نیست

دلیلش در کلاس بحث شد

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [25]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)
yhat = model.predict(X_test)
accuracy_score(y_test, yhat)

0.658008658008658

In [26]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.77      0.73      0.75       162
           1       0.44      0.49      0.46        69

    accuracy                           0.66       231
   macro avg       0.60      0.61      0.61       231
weighted avg       0.67      0.66      0.66       231



هر الگوریتم یادگیری معمولا یک سری پارامتر دارد

مثلا در الگوریتم کا همسایه عدد کا چند باشد؟

In [28]:
model = KNeighborsClassifier(n_neighbors=10)
model.fit(X_train, y_train)
yhat = model.predict(X_test)
accuracy_score(y_test, yhat)

0.7186147186147186

In [29]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       162
           1       0.53      0.49      0.51        69

    accuracy                           0.72       231
   macro avg       0.66      0.65      0.66       231
weighted avg       0.71      0.72      0.72       231



با کا بزرگتر کیفیت بهتر شد